// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ReadingProgress struct {
	ID          int64        `json:"id"`
	UserID      int64        `json:"user_id"`
	DayOfYear   int64        `json:"day_of_year"`
	Completed   sql.NullBool `json:"completed"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

type User struct {
	ID        int64          `json:"id"`
	GoogleID  sql.NullString `json:"google_id"`
	Email     sql.NullString `json:"email"`
	Name      sql.NullString `json:"name"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
