// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countCompletedDays = `-- name: CountCompletedDays :one
SELECT COUNT(*) FROM reading_progress WHERE user_id = ? AND completed = TRUE
`

func (q *Queries) CountCompletedDays(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedDays, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnonymousUser = `-- name: CreateAnonymousUser :one
INSERT INTO users (google_id, email, name)
VALUES (NULL, NULL, NULL)
RETURNING id, google_id, email, name, created_at
`

func (q *Queries) CreateAnonymousUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, createAnonymousUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_id, email, name)
VALUES (?, ?, ?)
RETURNING id, google_id, email, name, created_at
`

type CreateUserParams struct {
	GoogleID sql.NullString `json:"google_id"`
	Email    sql.NullString `json:"email"`
	Name     sql.NullString `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.GoogleID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getProgress = `-- name: GetProgress :many
SELECT id, user_id, day_of_year, completed, completed_at FROM reading_progress WHERE user_id = ?
`

func (q *Queries) GetProgress(ctx context.Context, userID int64) ([]ReadingProgress, error) {
	rows, err := q.db.QueryContext(ctx, getProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DayOfYear,
			&i.Completed,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgressByDay = `-- name: GetProgressByDay :one
SELECT id, user_id, day_of_year, completed, completed_at FROM reading_progress WHERE user_id = ? AND day_of_year = ?
`

type GetProgressByDayParams struct {
	UserID    int64 `json:"user_id"`
	DayOfYear int64 `json:"day_of_year"`
}

func (q *Queries) GetProgressByDay(ctx context.Context, arg GetProgressByDayParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, getProgressByDay, arg.UserID, arg.DayOfYear)
	var i ReadingProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayOfYear,
		&i.Completed,
		&i.CompletedAt,
	)
	return i, err
}

const getProgressByDayRange = `-- name: GetProgressByDayRange :many
SELECT id, user_id, day_of_year, completed, completed_at FROM reading_progress 
WHERE user_id = ? AND day_of_year >= ? AND day_of_year <= ?
`

type GetProgressByDayRangeParams struct {
	UserID      int64 `json:"user_id"`
	DayOfYear   int64 `json:"day_of_year"`
	DayOfYear_2 int64 `json:"day_of_year_2"`
}

func (q *Queries) GetProgressByDayRange(ctx context.Context, arg GetProgressByDayRangeParams) ([]ReadingProgress, error) {
	rows, err := q.db.QueryContext(ctx, getProgressByDayRange, arg.UserID, arg.DayOfYear, arg.DayOfYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DayOfYear,
			&i.Completed,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, name, created_at FROM users WHERE google_id = ?
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, email, name, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const mergeUserProgress = `-- name: MergeUserProgress :exec
UPDATE reading_progress SET user_id = ? WHERE user_id = ?
`

type MergeUserProgressParams struct {
	UserID   int64 `json:"user_id"`
	UserID_2 int64 `json:"user_id_2"`
}

func (q *Queries) MergeUserProgress(ctx context.Context, arg MergeUserProgressParams) error {
	_, err := q.db.ExecContext(ctx, mergeUserProgress, arg.UserID, arg.UserID_2)
	return err
}

const updateUserGoogleID = `-- name: UpdateUserGoogleID :exec
UPDATE users SET google_id = ?, email = ?, name = ? WHERE id = ?
`

type UpdateUserGoogleIDParams struct {
	GoogleID sql.NullString `json:"google_id"`
	Email    sql.NullString `json:"email"`
	Name     sql.NullString `json:"name"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserGoogleID,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.ID,
	)
	return err
}

const upsertProgress = `-- name: UpsertProgress :exec
INSERT INTO reading_progress (user_id, day_of_year, completed, completed_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, day_of_year) DO UPDATE SET
    completed = excluded.completed,
    completed_at = excluded.completed_at
`

type UpsertProgressParams struct {
	UserID      int64        `json:"user_id"`
	DayOfYear   int64        `json:"day_of_year"`
	Completed   sql.NullBool `json:"completed"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertProgress,
		arg.UserID,
		arg.DayOfYear,
		arg.Completed,
		arg.CompletedAt,
	)
	return err
}
